# This is a basic workflow that is manually triggered

name: 01 Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
#workflow dispatch significa que se ejecuta manual el job
  workflow_dispatch:
jobs:
  hola_mundo:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hola Mundo"
